name: Build Calaos Installer MacOS release

on: workflow_dispatch

jobs:
    compile:
        name: Build
        runs-on: macos-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - name: Import certificate
            uses: apple-actions/import-codesign-certs@v3
            with:
              p12-file-base64: ${{ secrets.MACOS_CERT_P12 }}
              p12-password: ${{ secrets.MACOS_CERT_PASS }}
              keychain: "build.keychain"
              keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASS }}
           
          - name: Install deps
            run: bash scripts/macos/install_deps.sh

          - name: Compile
            run: bash scripts/macos/build.sh

          - name: Notarize Release Build
            uses: lando/notarize-action@v2
            with:
              product-path: "build/MyApp.app"
              appstore-connect-username: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
              appstore-connect-password: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
              appstore-connect-team-id: ${{ secrets.MACOS_TEAM_ID }}
              tool: "altool"
              verbose: true

          - name: Deploy
            run: bash scripts/macos/deploy.sh
            env:
              UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
              MACOS_NOTARIZATION_USERNAME: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
              MACOS_NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}

