name: Build Calaos Installer MacOS release

on: workflow_dispatch

jobs:
    compile:
        name: Build
        runs-on: macos-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
           
          - name: Install deps
            run: scripts/macos/install_deps.sh

          - name: Compile
            run: scripts/macos/build.sh

          - name: Deploy
            run: scripts/macos/deploy.sh
