name: Build Calaos Installer release

on: workflow_dispatch

jobs:
    compile:
        name: Build
        runs-on: macos-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - name: Install Qt
            uses: jurplel/install-qt-action@v3
           
          - name: Install deps
            run: |
                 brew update
                 brew install kde-karchive

          - name: Compile
            run: |
                 mkdir build && cd build
                 qmake ../calaos_installer.pro CONFIG+=release
                 make -j8
                 qmake ../../machine_creator/machine_creator.pro CONFIG+=release
                 make -j8
        
