name: Build Calaos Installer release

on: workflow_dispatch

jobs:
    compile:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
            
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: calaos/winbuilder:latest
                options: -v ${{ github.workspace }}:/calaos_installer
                run: /scripts/build_installer.sh
